//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GH_Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GH_Studio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genesis 1:1 In the beginning God created the heaven and the earth.
        ///Genesis 1:2 And the earth was without form, and void; and darkness was on the face of the deep. And the Spirit of God moved on the face of the waters.
        ///Genesis 1:3 And God said, Let there be light: and there was light.
        ///Genesis 1:4 And God saw the light, that it was good: and God divided the light from the darkness.
        ///Genesis 1:5 And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.
        ///G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KJV {
            get {
                return ResourceManager.GetString("KJV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genesis 1:1 Nang pasimula ay nilikha ng Dios ang langit at ang lupa.
        ///Genesis 1:2 At ang lupa ay walang anyo at walang laman; at ang kadiliman ay sumasa ibabaw ng kalaliman; at ang Espiritu ng Dios ay sumasa ibabaw ng tubig.
        ///Genesis 1:3 At sinabi ng Dios Magkaroon ng liwanag; at nagkaroon ng liwanag.
        ///Genesis 1:4 At nakita ng Dios ang liwanag na mabuti, at inihiwalay ng Dios ang liwanag sa kadiliman.
        ///Genesis 1:5 At tinawag ng Dios ang liwanag na Araw, at tinawag niya ang kadiliman na Gabi. At nagkahapon at na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TAG {
            get {
                return ResourceManager.GetString("TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genesis 1:1 In the beginning God created the heavens and the earth.
        ///Genesis 1:2 Now the earth was formless and empty. Darkness was on the surface of the deep. God’s Spirit was hovering over the surface of the waters.
        ///Genesis 1:3 God said, “Let there be light,” and there was light.
        ///Genesis 1:4 God saw the light, and saw that it was good. God divided the light from the darkness.
        ///Genesis 1:5 God called the light “day,” and the darkness he called “night.” There was evening and there was morning, one day.
        ///Genesi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WEB {
            get {
                return ResourceManager.GetString("WEB", resourceCulture);
            }
        }
    }
}
